server {
  listen 8080;
  server_name _;
  access_log off;
  error_log /var/log/nginx/error.log warn;

  root /usr/share/nginx/html;
  index portal.html;

  location / {
    try_files $uri $uri/ /portal.html;
  }
}
